version = 1
name = "ledges_and_landings"
map_to_world_scale = 1.0
space_origin = [0.0, 0.0, 0.0]
notes = "Ledges and landings for grounded stability."

[[solids]]
id = "floor"
kind = "box"
pos = [0.0, -0.5, 0.0]
size = [60.0, 1.0, 40.0]
tags = ["ground"]

[[solids]]
id = "ledge_low"
kind = "box"
pos = [-10.0, 0.5, 0.0]
size = [6.0, 1.0, 6.0]
tags = ["ledge"]

[[solids]]
id = "ledge_mid"
kind = "box"
pos = [0.0, 1.5, 0.0]
size = [6.0, 3.0, 6.0]
tags = ["ledge"]

[[solids]]
id = "ledge_high"
kind = "box"
pos = [10.0, 2.5, 0.0]
size = [6.0, 5.0, 6.0]
tags = ["ledge"]

[[solids]]
id = "landing_bridge"
kind = "box"
pos = [0.0, 3.25, -8.0]
size = [18.0, 0.5, 4.0]
tags = ["landing"]
